[tool.poetry]
name = "everything-explained-in-manim"
version = "0.1.0"
description = ""
authors = ["arvind <arvind@datagenie.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
